package co.edu.usbbog.dbd.fiesteroAndante.view.window;

import co.edu.usbbog.dbd.fiesteroAndante.view.frame.ClienteAppJFrame;

public class MenuJPanel extends javax.swing.JPanel {
    private ClienteAppJFrame appJframe;
    /**
     * Creates new form Menu
     * @param appJframe
     */
    public MenuJPanel(ClienteAppJFrame appJframe) {
         this.appJframe = appJframe;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Salir = new javax.swing.JButton();
        BnProducto = new javax.swing.JButton();
        BnCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, 10));

        Salir.setBackground(new java.awt.Color(51, 51, 51));
        Salir.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 150, 40));

        BnProducto.setBackground(new java.awt.Color(51, 51, 51));
        BnProducto.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        BnProducto.setForeground(new java.awt.Color(255, 255, 255));
        BnProducto.setText("Producto");
        BnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnProductoActionPerformed(evt);
            }
        });
        add(BnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, 40));

        BnCliente.setBackground(new java.awt.Color(51, 51, 51));
        BnCliente.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        BnCliente.setForeground(new java.awt.Color(255, 255, 255));
        BnCliente.setText("Empleado");
        BnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnClienteActionPerformed(evt);
            }
        });
        add(BnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 150, 40));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 0, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú");
        kGradientPanel2.add(jLabel2);

        add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void BnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnProductoActionPerformed
        this.appJframe.irDeMenuAProducto(this);
    }//GEN-LAST:event_BnProductoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void BnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnClienteActionPerformed
        this.appJframe.irDeMenuAEmpleado(this);        
    }//GEN-LAST:event_BnClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnCliente;
    private javax.swing.JButton BnProducto;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
