package co.edu.usbbog.dbd.fiesteroAndante.view.window;

import co.edu.usbbog.dbd.fiesteroAndante.controller.dao.SucursalDAO;
import co.edu.usbbog.dbd.fiesteroAndante.controller.dao.SucursalDAOImpl;
import co.edu.usbbog.dbd.fiesteroAndante.model.ProductoDTO;
import co.edu.usbbog.dbd.fiesteroAndante.model.SucursalDTO;
import co.edu.usbbog.dbd.fiesteroAndante.view.frame.ClienteAppJFrame;
import java.sql.Date;

import java.time.ZoneId;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class ProductoJPanel extends javax.swing.JPanel {

    private ClienteAppJFrame appJframe;

    /**
     * Creates new form ProductoJPanel
     */
    public ProductoJPanel(ClienteAppJFrame appJframe) {
        this.appJframe = appJframe;
        initComponents();
        this.cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparatorTituloH = new javax.swing.JSeparator();
        jLabelTitulo = new javax.swing.JLabel();
        TxtProductoCal = new javax.swing.JTextField();
        jLabelCodigoProducto = new javax.swing.JLabel();
        jLabelCalidadProducto = new javax.swing.JLabel();
        jLabelPrecioProducto = new javax.swing.JLabel();
        jLabelFechaCaducidad = new javax.swing.JLabel();
        jLabelFechaCaducidad1 = new javax.swing.JLabel();
        jLabelFechaCaducidad2 = new javax.swing.JLabel();
        jLabelFechaCaducidad3 = new javax.swing.JLabel();
        jLabelFechaCaducidad4 = new javax.swing.JLabel();
        jLabelFechaCaducidad5 = new javax.swing.JLabel();
        jLabelFechaCaducidad6 = new javax.swing.JLabel();
        TxtProductoOrquesta = new javax.swing.JTextField();
        TxtCantidadProd = new javax.swing.JTextField();
        FechaViejo = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProd = new javax.swing.JTable();
        CrearProd = new javax.swing.JButton();
        EliminarProd = new javax.swing.JButton();
        ActualizarProd = new javax.swing.JButton();
        LimpiarCasProd = new javax.swing.JButton();
        MenuProd = new javax.swing.JButton();
        BuscarProd = new javax.swing.JButton();
        ComboProducto = new javax.swing.JComboBox<>();
        TxtProductoPrec = new javax.swing.JTextField();
        TipoProd = new javax.swing.JTextField();
        ComidaProd = new javax.swing.JTextField();
        TxtCodProducto = new javax.swing.JTextField();
        FechaCad = new com.toedter.calendar.JDateChooser();
        kGradientPanel1 = new keeptoo.KGradientPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparatorTituloH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 930, -1));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("PRODUCTO");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        TxtProductoCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoCalActionPerformed(evt);
            }
        });
        add(TxtProductoCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, -1));

        jLabelCodigoProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodigoProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoProducto.setText("Codigo Producto");
        add(jLabelCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabelCalidadProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCalidadProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCalidadProducto.setText("Fecha caducidad");
        add(jLabelCalidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabelPrecioProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioProducto.setText("Cantidad Producto");
        add(jLabelPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabelFechaCaducidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaCaducidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCaducidad.setText("Comida");
        add(jLabelFechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabelFechaCaducidad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaCaducidad1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCaducidad1.setText("Orquesta");
        add(jLabelFechaCaducidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabelFechaCaducidad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaCaducidad2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCaducidad2.setText("Sucursal");
        add(jLabelFechaCaducidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabelFechaCaducidad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaCaducidad3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCaducidad3.setText("Calidad producto");
        add(jLabelFechaCaducidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabelFechaCaducidad4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaCaducidad4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCaducidad4.setText("Precio producto");
        add(jLabelFechaCaducidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabelFechaCaducidad5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaCaducidad5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCaducidad5.setText("Añejamiento producto");
        add(jLabelFechaCaducidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jLabelFechaCaducidad6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaCaducidad6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCaducidad6.setText("Tipo");
        add(jLabelFechaCaducidad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        TxtProductoOrquesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoOrquestaActionPerformed(evt);
            }
        });
        add(TxtProductoOrquesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 190, -1));

        TxtCantidadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadProdActionPerformed(evt);
            }
        });
        add(TxtCantidadProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 260, -1));

        FechaViejo.setDateFormatString("yyyy/MM/dd ");
        add(FechaViejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 260, -1));

        TablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Producto", "Calidad Producto", "Precio Producto", "Fecha Caducidad", "Añejamiento", "Cantidad", "Tipo", "Comida", "Orquesta", "Sucursal"
            }
        ));
        jScrollPane1.setViewportView(TablaProd);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 850, 150));

        CrearProd.setText("Crear");
        CrearProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProdActionPerformed(evt);
            }
        });
        add(CrearProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        EliminarProd.setText("Eliminar");
        EliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProdActionPerformed(evt);
            }
        });
        add(EliminarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        ActualizarProd.setText("Actualizar");
        ActualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProdActionPerformed(evt);
            }
        });
        add(ActualizarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        LimpiarCasProd.setText("Limpiar");
        LimpiarCasProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarCasProdActionPerformed(evt);
            }
        });
        add(LimpiarCasProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        MenuProd.setText("Ir a menu");
        MenuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProdActionPerformed(evt);
            }
        });
        add(MenuProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, -1, -1));

        BuscarProd.setText("Buscar");
        BuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProdActionPerformed(evt);
            }
        });
        add(BuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        ComboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal" }));
        ComboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProductoActionPerformed(evt);
            }
        });
        add(ComboProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 190, -1));

        TxtProductoPrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoPrecActionPerformed(evt);
            }
        });
        add(TxtProductoPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, -1));

        TipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoProdActionPerformed(evt);
            }
        });
        add(TipoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 260, -1));

        ComidaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaProdActionPerformed(evt);
            }
        });
        add(ComidaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 260, -1));

        TxtCodProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodProductoActionPerformed(evt);
            }
        });
        add(TxtCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, -1));

        FechaCad.setDateFormatString("yyyy/MM/dd");
        add(FechaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 260, -1));
        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 950, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodProductoActionPerformed

    private void TxtProductoCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoCalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoCalActionPerformed

    private void TxtProductoPrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoPrecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoPrecActionPerformed

    private void TxtProductoOrquestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoOrquestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoOrquestaActionPerformed

    private void ComboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboProductoActionPerformed

    private void TxtCantidadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadProdActionPerformed

    private void TipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoProdActionPerformed

    private void ComidaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaProdActionPerformed

    private void CrearProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProdActionPerformed
       this.crear();
    }//GEN-LAST:event_CrearProdActionPerformed

    private void EliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProdActionPerformed
        this.eliminar();
    }//GEN-LAST:event_EliminarProdActionPerformed

    private void ActualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProdActionPerformed
       this.actualizar();
    }//GEN-LAST:event_ActualizarProdActionPerformed

    private void LimpiarCasProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarCasProdActionPerformed
        this.limpiar();
    }//GEN-LAST:event_LimpiarCasProdActionPerformed

    private void BuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProdActionPerformed
        this.buscar();
    }//GEN-LAST:event_BuscarProdActionPerformed

    private void MenuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProdActionPerformed
        this.appJframe.irDeProductoAMenu(this);
    }//GEN-LAST:event_MenuProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarProd;
    private javax.swing.JButton BuscarProd;
    private javax.swing.JComboBox<String> ComboProducto;
    private javax.swing.JTextField ComidaProd;
    private javax.swing.JButton CrearProd;
    private javax.swing.JButton EliminarProd;
    private com.toedter.calendar.JDateChooser FechaCad;
    private com.toedter.calendar.JDateChooser FechaViejo;
    private javax.swing.JButton LimpiarCasProd;
    private javax.swing.JButton MenuProd;
    private javax.swing.JTable TablaProd;
    private javax.swing.JTextField TipoProd;
    private javax.swing.JTextField TxtCantidadProd;
    private javax.swing.JTextField TxtCodProducto;
    private javax.swing.JTextField TxtProductoCal;
    private javax.swing.JTextField TxtProductoOrquesta;
    private javax.swing.JTextField TxtProductoPrec;
    private javax.swing.JLabel jLabelCalidadProducto;
    private javax.swing.JLabel jLabelCodigoProducto;
    private javax.swing.JLabel jLabelFechaCaducidad;
    private javax.swing.JLabel jLabelFechaCaducidad1;
    private javax.swing.JLabel jLabelFechaCaducidad2;
    private javax.swing.JLabel jLabelFechaCaducidad3;
    private javax.swing.JLabel jLabelFechaCaducidad4;
    private javax.swing.JLabel jLabelFechaCaducidad5;
    private javax.swing.JLabel jLabelFechaCaducidad6;
    private javax.swing.JLabel jLabelPrecioProducto;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorTituloH;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        List<ProductoDTO> productos = this.appJframe.mostrarProducto();
        DefaultTableModel model = (DefaultTableModel) TablaProd.getModel();
        model.setRowCount(0);
        for (ProductoDTO producto : productos) {
            model.addRow(new Object[]{producto.getCod_producto(), producto.getCalidad_producto(),
                producto.getPrecio_producto(), producto.getFecha_caducidad(), producto.getAniejamiento_producto(),
                producto.getCantidad_producto(), producto.getTipo(), producto.getComida(), producto.getOrquesta()
              , producto.getSucursal().getId_sucursal()});
        }

        // Llennar combox 
        ComboProducto.removeAllItems();
        ComboProducto.addItem("Sucursal");
        for (ProductoDTO producto : productos) {
            ComboProducto.addItem(producto.getSucursal().getId_sucursal() + "");
        }
    }

    private void limpiar() {
        TxtCodProducto.setText("");
        TxtProductoCal.setText("");
        TxtProductoPrec.setText("");
        FechaCad.setDate(null);
        FechaViejo.setDate(null);
        TxtCantidadProd.setText("");
        TipoProd.setText("");
        ComidaProd.setText("");
        TxtProductoOrquesta.setText("");
        ComboProducto.setSelectedIndex(0);

    }

    private boolean validar() {
        return !(TxtCodProducto.getText().equals("")
                || TxtProductoCal.getText().equals("")
                || TxtProductoPrec.getText().equals("")
                || FechaCad.getDateFormatString() == null
                || FechaViejo.getDateFormatString() == null
                || TxtCantidadProd.getText().equals("")
                || TipoProd.getText().equals("")
                || ComidaProd.getText().equals("")
                || TxtProductoOrquesta.getText().equals(""))
                || ComboProducto.getSelectedIndex() == 0;
    }
    //ic es la interfaz, jDate el JDatechooser

    /*java.util.Date fechaActual= new java.util.Date(System.currentTimeMillis());
java.sql.Date fechaSql= java.sql.Date.valueOf(fechaActual.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());

String dia = Integer.toString(FechaCad.getCalendar().get(Calendar.DAY_OF_MONTH));
String mes = Integer.toString(FechaCad.getCalendar().get(Calendar.MONTH)+1);
String año = Integer.toString(FechaCad.getCalendar().get(Calendar.YEAR));
String fecha=(año+"-"+mes+""+dia);*/
    private void crear() {
        java.util.Date fecha = FechaCad.getDate();
        long formato = fecha.getTime();
        java.sql.Date entrada = new java.sql.Date(formato);
        java.util.Date fecha2 = FechaViejo.getDate();
        long f = fecha2.getTime();
        java.sql.Date a = new java.sql.Date(f);
        
        SucursalDTO sucursal;
        SucursalDAO s  = new SucursalDAOImpl();
        sucursal= s.find(Integer.parseInt(ComboProducto.getItemAt(ComboProducto.getSelectedIndex())));
        
        if (this.validar()) {

            try {
                Object salida;
                salida = this.appJframe.crearProducto(
                        Integer.parseInt(TxtCodProducto.getText()),
                        TxtProductoCal.getText(),
                        Double.parseDouble(TxtProductoPrec.getText()),
                        entrada,
                        a,
                        Integer.parseInt(TxtCantidadProd.getText()),
                        TipoProd.getText(),
                        ComidaProd.getText(),
                        TxtProductoOrquesta.getText(),
                        sucursal);

                JOptionPane.showMessageDialog(null, salida, "Crear producto", 1);
                this.cargarDatos();
                this.limpiar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Los campos de número y saldo deben ser numéricos", "ERROR", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "ERROR", 2);
        }
    }

    private void eliminar() {
        if (!TxtCodProducto.getText().equals("")) {
            try {
                String salida = this.appJframe.eliminarProducto(Integer.parseInt(TxtCodProducto.getText()));
                JOptionPane.showMessageDialog(null, salida, "Eliminar producto", 1);
                this.cargarDatos();
                this.limpiar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El codido de producto  debe ser un valor numérico", "ERROR", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un codigo de producto", "ERROR", 2);
        }
    }

    private void buscar() {
        if (!TxtCodProducto.getText().equals("")) {
            try {
                ProductoDTO producto = this.appJframe.buscarProducto(Integer.parseInt(TxtCodProducto.getText()));
                if (producto != null) {
                    JOptionPane.showMessageDialog(null, "Encontrado", "Buscar producto", 1);
                    TxtProductoCal.setText(producto.getCalidad_producto());
                    TxtProductoPrec.setText(Double.toString(producto.getPrecio_producto()));
                    TxtCantidadProd.setText(Integer.toString(producto.getCantidad_producto()));
                    TipoProd.setText(producto.getTipo());
                    ComidaProd.setText(producto.getComida());
                    FechaCad.setDate(producto.getFecha_caducidad());
                    FechaViejo.setDate(producto.getFecha_caducidad());
                    TxtProductoOrquesta.setText(producto.getOrquesta() + "");
                    for (int i = 0; i < ComboProducto.getItemCount(); i++) {
                        if (ComboProducto.getItemAt(i).equals(producto.getSucursal().getId_sucursal() + "")) {
                            ComboProducto.setSelectedIndex(i);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No encontrado", "Buscar producto", 1);
                    this.limpiar();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El código de producto debe ser un valor numérico", "ERROR", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un codigo de producto", "ERROR", 2);
        }
    }


    private void actualizar() {
        
        java.util.Date fecha = FechaCad.getDate();
        long formato = fecha.getTime();
        java.sql.Date entrada = new java.sql.Date(formato);
        java.util.Date fecha2 = FechaViejo.getDate();
        long f = fecha2.getTime();
        java.sql.Date a = new java.sql.Date(f);
        
        SucursalDTO sucursal;
        SucursalDAO s  = new SucursalDAOImpl();
        sucursal= s.find(Integer.parseInt(ComboProducto.getItemAt(ComboProducto.getSelectedIndex())));
        
        if (this.validar()) {
            try {

                String salida = this.appJframe.modificarProducto(
                        Integer.parseInt(TxtCodProducto.getText()),
                        TxtProductoCal.getText(),
                        Double.parseDouble(TxtProductoPrec.getText()),
                        entrada,
                        a,
                        Integer.parseInt(TxtCantidadProd.getText()),
                        TipoProd.getText(),
                        ComidaProd.getText(),
                        TxtProductoOrquesta.getText(),
                        sucursal);

                JOptionPane.showMessageDialog(null, salida, "MODIFICACIÓN EXITOSA", 1);
                this.cargarDatos();
                this.limpiar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Los campos de código,precio y cantidad deben ser numéricos", "ERROR", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "ERROR", 2);
        }
    }
    
}
